config/routes.rb
Rails.application.routes.draw do

  root to: 'games#current'

  get '/teams/:id', to: 'teams#show', as: 'team'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :home_games, foreign_key: "home_team_id", class_name: "Game"
  has_many :away_games, foreign_key: "away_team_id", class_name: "Game"

  def total_points
    home_games.sum(:team1points) + away_games.sum(:team2points) 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def current
    @games = Game.where(datetime: Date.today..1.week.from_now)
    @teams = Team.all.sort_by(&:total_points).reverse
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.find(params[:id])
    @games = Game.where("home_team_id = ? OR away_team_id = ?", params[:id], params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/current.html.erb
<h1>Current Schedule</h1>

<table>
  <thead>
    <tr>
      <th>Date/Time</th>
      <th>Team 1</th>
      <th>Team 2</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.datetime.strftime('%m/%d/%y - %I:%M') %></td>
        <td><%= link_to game.home_team.name, team_path(game.home_team.id) %></td>
        <td><%= link_to game.away_team.name, team_path(game.away_team.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Teams</h1>
<ol>
  <% @teams.each do |team| %>
    <li><%= link_to team.name, team_path(team)%> <%= team.total_points %></li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolleyvall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>